"""Add public tables

Revision ID: cdef3b7288aa
Revises: 
Create Date: 2023-10-13 15:00:03.246286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdef3b7288aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    public_users = """
    CREATE TABLE IF NOT EXISTS public.public_users (
       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       uuid uuid UNIQUE NOT NULL,
       first_name varchar(100),
       last_name varchar(100),
       email varchar(256),
       phone varchar(16),
       password varchar(256),
       service_token varchar(256),
       service_token_valid_to TIMESTAMPTZ,
       is_active BOOLEAN NOT NULL,
       is_verified BOOLEAN NOT NULL,
       tos BOOLEAN NOT NULL,
       tenant_id varchar(64),
       tz varchar(64),
       lang varchar(8),
       created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
       updated_at TIMESTAMPTZ,
       deleted_at TIMESTAMPTZ
      );
    """
    op.execute(public_users)

    public_users_index = """
      CREATE INDEX IF NOT EXISTS public_users_tenant_id_idx ON public.public_users (tenant_id);
    """
    op.execute(public_users_index)


def downgrade() -> None:
    pass
